---
apiVersion: v1
kind: List
items:
- kind: Service
  apiVersion: v1
  metadata:
    annotations:
      prometheus.io/scrape: "true"
    labels:
      app: heketi-metrics-exporter
    name: heketi-metrics-exporter
  spec:
    clusterIP: None
    ports:
    - name: scrape
      port: 9189
      protocol: TCP
      targetPort: 9189
    selector:
      app: heketi-metrics-exporter
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: heketi-metrics-exporter
    labels:
      app: heketi-metrics-exporter
  spec:
    replicas: 1
    selector:
      app: heketi-metrics-exporter
    template:
      metadata:
        labels:
          app: heketi-metrics-exporter
      spec:
        containers:
          - name: heketi-metrics-exporter
            image: allen13/heketi-metrics-exporter:latest
            imagePullPolicy: Always
            env:
            - name: HEKETI_CLI_USER
              value: admin
            - name: HEKETI_CLI_KEY
              value: "<CHANGE ME>"
            - name: HEKETI_CLI_SERVER
              value: "<CHANGE ME>"
            ports:
              - containerPort: 9189
                name: scrape
            resources:
              requests:
                cpu: 10m
                memory: 200Mi
            terminationMessagePath: /dev/termination-log
            securityContext:
              capabilities: {}
              privileged: false
        restartPolicy: Always
